---
name: Feature request
about: Suggest an idea
title: '[Feature] '
labels: enhancement
assignees: MostafaAshry513
---

**Is your feature request related to a problem?**
What problem would this solve?

**Describe the solution**
What should happen?

**Keyboard shortcut**
What should the keyboard shortcut be? (e.g. Ctrl+Shift+X)

**Additional context**
Any other details.
